"""
Telegram Notifier Module.
Sends instant high-priority alerts directly to the user's phone via Telegram Bot API.
"""

import os
import requests
from typing import Dict, Any, Optional

def send_telegram_message(
    message: str,
    bot_token: Optional[str] = None,
    chat_id: Optional[str] = None
) -> bool:
    """
    Sends a formatted message to Telegram.
    Pulls credentials from parameters, environment variables, or config.
    """
    # Read .env file if env vars are not set
    env_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env")
    if os.path.exists(env_path):
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    if k.strip() not in os.environ:
                        os.environ[k.strip()] = v.strip()

    token = bot_token or os.getenv("TELEGRAM_BOT_TOKEN")
    chat = chat_id or os.getenv("TELEGRAM_CHAT_ID")

    if not token or not chat:
        # Telegram not configured yet
        return False

    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = {
        "chat_id": chat,
        "text": message,
        "parse_mode": "Markdown",
        "disable_web_page_preview": True
    }

    try:
        response = requests.post(url, json=payload, timeout=10)
        return response.status_code == 200
    except Exception as e:
        print(f"Failed to send Telegram alert: {e}")
        return False

def format_telegram_alert(alert: Dict[str, Any]) -> str:
    """
    Formats the trade signal into a high-visibility Telegram notification.
    """
    return f"""🚨 *TRADE ALERT: {alert['ticker']}* 🚨

📈 *Type*: `{alert['type']}`
💰 *Current Price*: `{alert['current_price']}`
🎯 *Target 1 (2R)*: `{alert['target']}`
🛑 *Stop-Loss*: `{alert['stop_loss']}`
📊 *Relative Volume*: `{alert['rvol']:.1f}x`
⚡ *Verdict*: `{alert['verdict']}`

💡 *Agent Rationale*:
_{alert['summary']}_

_Generated by Antigravity Autonomous Agent Squad_"""
